### ISSUE TITLE
Visit the demo website and report an error

### ISSUE THREAD

**Issue by Zuojiangtao** [usememos/memos#1603]
### Describe the bug

Unexpected Application Error!
Cannot destructure property 'localSetting' of 'd.state.user' as it is undefined.

```
TypeError: Cannot destructure property 'localSetting' of 'd.state.user' as it is undefined.
    at rye (https://demo.usememos.com/assets/index-01ae03bf.js:321:421)
    at zM (https://demo.usememos.com/assets/index-01ae03bf.js:83:19538)
    at N7 (https://demo.usememos.com/assets/index-01ae03bf.js:85:44055)
    at R7 (https://demo.usememos.com/assets/index-01ae03bf.js:85:39787)
    at SK (https://demo.usememos.com/assets/index-01ae03bf.js:85:39715)
    at bT (https://demo.usememos.com/assets/index-01ae03bf.js:85:39568)
    at iA (https://demo.usememos.com/assets/index-01ae03bf.js:85:35933)
    at b7 (https://demo.usememos.com/assets/index-01ae03bf.js:85:34882)
    at T (https://demo.usememos.com/assets/index-01ae03bf.js:70:1554)
    at MessagePort.H (https://demo.usememos.com/assets/index-01ae03bf.js:70:1916)
```

### Steps to reproduce

1. 直接访问https://demo.usememos.com/explore；
2. 报错；

**Comment by sixmillions** [comment]
Version 0.12.2

Direct access redirected to/explore, error occurred, like your error
Visit /auth first, and after logging in, there will be no errors reported

what happen?

**Comment by Zuojiangtao** [comment]
> 

This service has been suspended.

**Comment by Zuojiangtao** [comment]
> Version 0.12.2
> 
> Direct access redirected to/explore, error occurred, like your error Visit /auth first, and after logging in, there will be no errors reported
> 
> what happen?

This service has been suspended.
