### ISSUE TITLE
unhandle error

### ISSUE THREAD

**Issue by sparrowyang** [usememos/memos#1649]
### Describe the bug

Unhandled Thrown Error!
Cannot read properties of undefined (reading 'mode')
TypeError: Cannot read properties of undefined (reading 'mode')
    at J (http://my.site:8000/assets/Auth-6c3f0140.js:1:391)
    at n7 (http://my.site:8000/assets/index-7a6dd5c0.js:77:19518)
    at S8 (http://my.site:8000/assets/index-7a6dd5c0.js:79:3139)
    at JC (http://my.site:8000/assets/index-7a6dd5c0.js:79:44490)
    at KC (http://my.site:8000/assets/index-7a6dd5c0.js:79:39724)
    at $z (http://my.site:8000/assets/index-7a6dd5c0.js:79:39652)
    at X4 (http://my.site:8000/assets/index-7a6dd5c0.js:79:39506)
    at $8 (http://my.site:8000/assets/index-7a6dd5c0.js:79:35874)
    at UC (http://my.site:8000/assets/index-7a6dd5c0.js:79:34825)
    at x (http://my.site:8000/assets/index-7a6dd5c0.js:64:1559)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own errorElement props on <Route>

### Steps to reproduce

open mysite

**Comment by sparrowyang** [comment]
i run a old version
