### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jlongnan** [usememos/memos#1799]
### Describe the bug

After posted some content with the OpenAPI URL, I got the following error on the page:
Unexpected Application Error!
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at mn (https://memos.....cn/assets/index-101bd4f5.js:319:2650)
    at mn (https://memos.....cn/assets/index-101bd4f5.js:320:231)
    at Object.X1e [as renderer] (https://memos.....cn/assets/index-101bd4f5.js:319:1517)
    at mn (https://memos.....cn/assets/index-101bd4f5.js:320:244)
    at mn (https://memos.....cn/assets/index-101bd4f5.js:320:256)
    at Object.P1e [as renderer] (https://memos.....cn/assets/index-101bd4f5.js:318:87823)
    at mn (https://memos.....cn/assets/index-101bd4f5.js:320:42)
    at mn (https://memos.....cn/assets/index-101bd4f5.js:320:54)
    at mn (https://memos.....cn/assets/index-101bd4f5.js:320:54)
    at mn (https://memos.....cn/assets/index-101bd4f5.js:320:54)

### Steps to reproduce

1. Post content with OpenAPI
2. Open memos in the browser.

**Comment by athurg** [comment]
Maybe you can paste the content you have post, and with the open api you call will be more better
