### ISSUE TITLE
save bug

### ISSUE THREAD

**Issue by Jerning** [usememos/memos#2060]
### Describe the bug

Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ur (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:83:20135)
    at px (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:83:20389)
    at Object.useState (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:83:27204)
    at We.useState (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:9:6382)
    at f$ (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:282:1777)
    at et (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:312:339)
    at Object.RSe [as renderer] (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:324:85842)
    at Tn (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:326:42)
    at Tn (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:326:54)
    at Tn (https://memos.jerningblog.com:21443/assets/index-f1b19e34.js:326:54)

### Steps to reproduce

1. edit
2. save

**Comment by chengda** [comment]
same problem
