### ISSUE TITLE
after i edit a memo and save it, it crash!

### ISSUE THREAD

**Issue by Crazyokd** [usememos/memos#2069]
### Describe the bug

Unexpected Application Error!
Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
Error: Minified React error #310; visit https://reactjs.org/docs/error-decoder.html?invariant=310 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ur (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:83:20135)
    at px (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:83:20389)
    at Object.useState (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:83:27204)
    at We.useState (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:9:6382)
    at f$ (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:282:1777)
    at et (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:312:339)
    at Object.RSe [as renderer] (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:324:85842)
    at Tn (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:325:2850)
    at Tn (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:326:54)
    at Tn (http://memos.sxrekord.com:7080/assets/index-f1b19e34.js:326:54)

### Steps to reproduce

1. publish a memo
2. edit it and append some code snippet, such as below:
```
#! /usr/bin/env bash

sleep 10

echo "execute over"

sleep 5

echo "execute over twice"
```
3. The crash happend!

**Comment by itodouble** [comment]
![image](https://github.com/usememos/memos/assets/13508120/c0efa8a0-3944-4f80-b63a-33a817ec66cb)
me too
