### ISSUE TITLE
Panic when posting new memos after upgrading to 0.18.2

### ISSUE THREAD

**Issue by wolfsilver** [usememos/memos#2784]
### Describe the bug

Using telegram is OK.

use web client will restart.

```
memos  | panic: runtime error: invalid memory address or nil pointer dereference
memos  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1127e40]
memos  | 
memos  | goroutine 308 [running]:
memos  | github.com/usememos/memos/api/v2.(*APIV2Service).getDisablePublicMemosSystemSettingValue(0xc0003ec840, {0x19019e8, 0xc0005ca2d0})
memos  |        /backend-build/api/v2/memo_service.go:611 +0x80
memos  | github.com/usememos/memos/api/v2.(*APIV2Service).CreateMemo(0xc0003ec840, {0x19019e8?, 0xc0005ca2d0}, 0xc00052e100)
memos  |        /backend-build/api/v2/memo_service.go:57 +0x165
memos  | github.com/usememos/memos/proto/gen/api/v2._MemoService_CreateMemo_Handler.func1({0x19019e8, 0xc0005ca2d0}, {0x15a6ba0?, 0xc00052e100})
memos  |        /backend-build/proto/gen/api/v2/memo_service_grpc.pb.go:279 +0x72
memos  | github.com/usememos/memos/api/v2.(*GRPCAuthInterceptor).AuthenticationInterceptor(0xc00033a780, {0x19019e8, 0xc0004a5e30}, {0x15a6ba0, 0xc00052e100}, 0xc0007e8ee0, 0xc0000309f0)
memos  |        /backend-build/api/v2/acl.go:80 +0x396
memos  | github.com/usememos/memos/proto/gen/api/v2._MemoService_CreateMemo_Handler({0x1672f60?, 0xc0003ec840}, {0x19019e8, 0xc0004a5e30}, 0xc00049d400, 0xc0003e2d20)
memos  |        /backend-build/proto/gen/api/v2/memo_service_grpc.pb.go:281 +0x135
memos  | google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002d9200, {0x19019e8, 0xc0004a5d40}, {0x1909560, 0xc0007a7520}, 0xc0006f3d40, 0xc0003eca80, 0x2361020, 0xc00052e0c0)
memos  |        /go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1372 +0xe03
memos  | google.golang.org/grpc.(*Server).handleStream(0xc0002d9200, {0x1909560, 0xc0007a7520}, 0xc0006f3d40)
memos  |        /go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1783 +0xfec
memos  | google.golang.org/grpc.(*Server).serveStreams.func2.1()
memos  |        /go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1016 +0x59
memos  | created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 112
memos  |        /go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:1027 +0x115
memos exited with code 2
memos  | ---
memos  | Server profile
memos  | data: /var/opt/memos
memos  | dsn: /var/opt/memos/memos_prod.db
memos  | addr: 
memos  | port: 5230
memos  | mode: prod
memos  | driver: sqlite
memos  | version: 0.18.2
memos  | metric: true
```

### Steps to reproduce

1. posting a new memo

### The version of Memos you're using

0.18.2

**Comment by boojack** [comment]
@wolfsilver Thanks for your report. Fixed with https://github.com/usememos/memos/commit/f28b65405706b34c811d5487648ba5b182538ef4

**Comment by erbanku** [comment]
The issue seems to have been fixed.
