### ISSUE TITLE
Unexpected Application Error! Error: Go program has already exited

### ISSUE THREAD

**Issue by Derekmini** [usememos/memos#2880]
### Describe the bug

经v0.18.2升级到v0.19.0后，出现内存沾满的问题，后又退回v0.18.2，出现无法新建Memo的情况：constraint failed: UNIQUE constraint failed: memo.resource_name (2067)，但之前的Memo数据还能继续查看；现升级到v0.19.1后，已经没有内存/CPU占用高的问题，但无法查看Memo，具体表现在：打开主页后，会一直显示如下内容：
<p align="center">
  <img width="500" alt="image" src="https://github.com/usememos/memos/assets/30514323/254c83f3-bbf0-490c-85a4-43f7e5773afd">
</p>

直到转换数据库的程序报错退出，提示如下内容：
```log
Unexpected Application Error!
Go program has already exited
Error: Go program has already exited
    at globalThis.Go._resume (http://10.1.1.13:5233/wasm_exec.js:543:11)
    at http://10.1.1.13:5233/wasm_exec.js:556:8
    at Gb (http://10.1.1.13:5233/assets/useDebounce-g5raXbxh.js:269:10250)
    at Xh (http://10.1.1.13:5233/assets/index-xR6IJEMV.js:75:21707)
    at dj (http://10.1.1.13:5233/assets/index-xR6IJEMV.js:77:3491)
    at cj (http://10.1.1.13:5233/assets/index-xR6IJEMV.js:77:2624)
    at aj (http://10.1.1.13:5233/assets/index-xR6IJEMV.js:77:2093)
    at Wk (http://10.1.1.13:5233/assets/index-xR6IJEMV.js:77:52182)
    at Vk (http://10.1.1.13:5233/assets/index-xR6IJEMV.js:77:43777)
    at Uk (http://10.1.1.13:5233/assets/index-xR6IJEMV.js:77:43700)
```
<p align="center">
  <img width="745" alt="image" src="https://github.com/usememos/memos/assets/30514323/03c8dd4a-c85f-4c64-b9a9-ec9e4d32b26b">
</p>

### Steps to reproduce

1. 在浏览器打开 ip:port；
2. 显示“正在获取数据”；
3. 提示“Unexpected Application Error!”

### The version of Memos you're using

v0.19.1

**Comment by cowardmrx** [comment]
So did I

**Comment by Derekmini** [comment]
我刚才尝试通过 SQLite Expert Personal 软件手动将部分Memo复制到新建的数据库中，是可以成功启动的，但是当我把全部内容复制过去后，就会出现上述问题。我的总Memo条目有800左右，最初复制过去的Memo有10条左右。

**Comment by Derekmini** [comment]
另外，我发现，之所以出现“constraint failed: UNIQUE constraint failed: memo.resource_name (2067)”的问题，是因为经历了从v0.18.2->v0.19.0->v0.18.2的过程后，新添加第一条Memo的`resource_name`是空的，但其他的`content`等字段都正常。

所以，等再创建新Memo时，系统分配的`resource_name`可能仍是空的，这就与`UNIQUE`限制冲突了，导致无法创建新Memo。

我不太清楚为什么创建操作会有这样的不完整操作，关于以上描述内容的图片示意为[注意最后侧空白的内容应为`resource_name`字符串内容，图片中为空白]：

<img width="1236" alt="image" src="https://github.com/usememos/memos/assets/30514323/cd80ddd7-a460-450b-8be2-52b2902aedef">

**Comment by lincolnthalles** [comment]
> 另外，我发现，之所以出现“constraint failed: UNIQUE constraint failed: memo.resource_name (2067)”的问题，是因为经历了从v0.18.2->v0.19.0->v0.18.2的过程后，新添加第一条Memo的`resource_name`是空的，但其他的`content`等字段都正常。
> 
> 所以，等再创建新Memo时，系统分配的`resource_name`可能仍是空的，这就与`UNIQUE`限制冲突了，导致无法创建新Memo。
> 
> 我不太清楚为什么创建操作会有这样的不完整操作，关于以上描述内容的图片示意为[注意最后侧空白的内容应为`resource_name`字符串内容，图片中为空白]：
> 
> <img alt="image" width="1240" src="https://private-user-images.githubusercontent.com/30514323/301374761-9b75ebe3-1fc8-4db3-b335-05fe3dec02b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjQ3NDQsIm5iZiI6MTcwNjc2NDQ0NCwicGF0aCI6Ii8zMDUxNDMyMy8zMDEzNzQ3NjEtOWI3NWViZTMtMWZjOC00ZGIzLWIzMzUtMDVmZTNkZWMwMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA1MTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOTYyYWIxNmM0YmJjZjQ5ZTkzOTQzNWQwNjAwZjFiMDNkNTg2Y2UxYjNkYjFjMjY4ZmFiNWFkNzEyMmNiMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_hv5Iq5cnergA5CIG0nR7IAHmNwtrTNyr4Z5DG7T2E">

# Downgrading queries from v0.19.1/v0.19.0 => 0.18.2

**Remember to backup your database first.**

For SQLite and Postres:
```sql
DROP INDEX idx_memo_resource_name;
ALTER TABLE memo DROP COLUMN resource_name;

DROP INDEX idx_resource_resource_name;
ALTER TABLE resource DROP COLUMN resource_name;
```
For MySQL:
```sql
DROP INDEX idx_memo_resource_name ON memo;
ALTER TABLE memo DROP COLUMN resource_name;

DROP INDEX idx_resource_resource_name ON resource;
ALTER TABLE resource DROP COLUMN resource_name;
```

After downgrading, you should wait for at least v0.19.2 before upgrading, as the front-end is broken in v0.19.1.

But if you really really want v0.19.0 (also have its issues, but it works for most people), you can try this:

- Use the downgrade queries;
- Pull the v0.19.1 image;
- Start the container and wait for the migration to run. Check if the front-end loads to confirm it's done.
- Finally pull the v0.19.0 image over it.

Front-end is broken in 0.19.1, but it's running a minimal migration that should run to completion without issues.

**Comment by Derekmini** [comment]
> > 另外，我发现，之所以出现“constraint failed: UNIQUE constraint failed: memo.resource_name (2067)”的问题，是因为经历了从v0.18.2->v0.19.0->v0.18.2的过程后，新添加第一条Memo的`resource_name`是空的，但其他的`content`等字段都正常。
> > 所以，等再创建新Memo时，系统分配的`resource_name`可能仍是空的，这就与`UNIQUE`限制冲突了，导致无法创建新Memo。
> > 我不太清楚为什么创建操作会有这样的不完整操作，关于以上描述内容的图片示意为[注意最后侧空白的内容应为`resource_name`字符串内容，图片中为空白]：
> > <img alt="image" width="1240" src="https://private-user-images.githubusercontent.com/30514323/301374761-9b75ebe3-1fc8-4db3-b335-05fe3dec02b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NjQ3NDQsIm5iZiI6MTcwNjc2NDQ0NCwicGF0aCI6Ii8zMDUxNDMyMy8zMDEzNzQ3NjEtOWI3NWViZTMtMWZjOC00ZGIzLWIzMzUtMDVmZTNkZWMwMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA1MTQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzOTYyYWIxNmM0YmJjZjQ5ZTkzOTQzNWQwNjAwZjFiMDNkNTg2Y2UxYjNkYjFjMjY4ZmFiNWFkNzEyMmNiMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N_hv5Iq5cnergA5CIG0nR7IAHmNwtrTNyr4Z5DG7T2E">
> 
> # Downgrading queries from v0.19.1/v0.19.0 => 0.18.2
> **Remember to backup your database first.**
> 
> For SQLite and Postgres:
> 
> ```sql
> DROP INDEX idx_memo_resource_name;
> ALTER TABLE memo DROP COLUMN resource_name;
> 
> DROP INDEX idx_resource_resource_name;
> ALTER TABLE resource DROP COLUMN resource_name;
> ```
> 
> For MySQL:
> 
> ```sql
> DROP INDEX idx_memo_resource_name ON memo;
> ALTER TABLE memo DROP COLUMN resource_name;
> 
> DROP INDEX idx_resource_resource_name ON resource;
> ALTER TABLE resource DROP COLUMN resource_name;
> ```
> 
> After downgrading, you should wait for at least v0.19.2 before upgrading, as the front-end is broken in v0.19.1.
> 
> But if you really really want v0.19.0 (also have its issues, but it works for most people), you can try this:
> 
> * Use the downgrade queries;
> * Pull the v0.19.1 image;
> * Start the container and wait for the migration to run. Check if the front-end loads to confirm it's done.
> * Finally pull the v0.19.0 image over it.
> 
> Front-end is broken in 0.19.1, but it's running a minimal migration that should run to completion without issues.

# For Downgrading queries from v0.19.1/v0.19.0 => 0.18.2

Thank you very much for providing the code to downgrade to v0.18.2. I have successfully downgraded Memos to v0.18.2 by excluding the SQLite code. Thanks a lot, Lincoln!
