### ISSUE TITLE
v0.19.1 front-end is broken

### ISSUE THREAD

**Issue by lincolnthalles** [usememos/memos#2883]
### Describe the bug

This happens even in demo mode, and it's already affecting https://demo.usememos.com, on both mobile and desktop.

The navigation seems to work fine, but if you open a memo directly and then hit refresh, or just access its `/m/uuid` link, this error will show up:

This seems to be related to gomark.

```
Unexpected Application Error!

wasm_exec.js:1 Uncaught SyntaxError: Unexpected token '<'
ZvH7a6VWMuX5aArtECTj4N:37 Uncaught ReferenceError: Go is not defined
    at ZvH7a6VWMuX5aArtECTj4N:37:18
index-xR6IJEMV.js:77 TypeError: window.parse is not a function
    at Gb (useDebounce-g5raXbxh.js:269:10250)
    at Xh (index-xR6IJEMV.js:75:21707)
    at dj (index-xR6IJEMV.js:77:3491)
    at cj (index-xR6IJEMV.js:77:2624)
    at aj (index-xR6IJEMV.js:77:2093)
    at Wk (index-xR6IJEMV.js:77:52182)
    at Vk (index-xR6IJEMV.js:77:43777)
    at Uk (index-xR6IJEMV.js:77:43700)
    at Jk (index-xR6IJEMV.js:77:43542)
    at Ok (index-xR6IJEMV.js:77:39552)
Mi @ index-xR6IJEMV.js:77
index-xR6IJEMV.js:288 React Router caught the following error during render TypeError: window.parse is not a function
    at Gb (useDebounce-g5raXbxh.js:269:10250)
    at Xh (index-xR6IJEMV.js:75:21707)
    at dj (index-xR6IJEMV.js:77:3491)
    at cj (index-xR6IJEMV.js:77:2624)
    at aj (index-xR6IJEMV.js:77:2093)
    at Wk (index-xR6IJEMV.js:77:52182)
    at Vk (index-xR6IJEMV.js:77:43777)
    at Uk (index-xR6IJEMV.js:77:43700)
    at Jk (index-xR6IJEMV.js:77:43542)
    at Ok (index-xR6IJEMV.js:77:39552) Object
componentDidCatch @ index-xR6IJEMV.js:288

```

### Steps to reproduce

1. https://demo.usememos.com
2. Click on a memo header, to open its /m/ link
3. Hit refresh

### The version of Memos you're using

v0.19.1

**Comment by xwjdsh** [comment]
Same issue, profile page broken, 

https://demo.usememos.com/u/memos-demo
```
Unexpected Application Error!
window.parse is not a function. (In 'window.parse(t)', 'window.parse' is undefined)
Gb@https://demo.usememos.com/assets/useDebounce-g5raXbxh.js:269:10255
Xh@https://demo.usememos.com/assets/index-xR6IJEMV.js:75:21709
dj@https://demo.usememos.com/assets/index-xR6IJEMV.js:77:3493
Vk@https://demo.usememos.com/assets/index-xR6IJEMV.js:77:43779
Uk@https://demo.usememos.com/assets/index-xR6IJEMV.js:77:43702
Jk@https://demo.usememos.com/assets/index-xR6IJEMV.js:77:43544
Ok@https://demo.usememos.com/assets/index-xR6IJEMV.js:77:39554
Fk@https://demo.usememos.com/assets/index-xR6IJEMV.js:77:40448
jg@https://demo.usememos.com/assets/index-xR6IJEMV.js:75:3534
@https://demo.usememos.com/assets/index-xR6IJEMV.js:77:37704
```

**Comment by klsdfjo** [comment]
I have the same problem, how can I fix it?

**Comment by ertuil** [comment]
> Maybe fixed with [554f93e](https://github.com/usememos/memos/commit/554f93eccc02bc0705a808bc66641836bf32023c)

After a quick check, it seems that this problem is not fixed with 554f93e
I get a new console errors:

```
Uncaught SyntaxError: Unexpected token '<' (at wasm_exec.js:1:1)
index-pZwLOWcE.js:324  Uncaught (in promise) TypeError: window.Go is not a constructor
    at dt (index-pZwLOWcE.js:324:139697)
    at index-pZwLOWcE.js:324:139880
    at Rj (index-pZwLOWcE.js:77:26705)
    at Ik (index-pZwLOWcE.js:77:46639)
    at index-pZwLOWcE.js:77:44795
    at Mt (index-pZwLOWcE.js:62:1729)
    at MessagePort.Wt (index-pZwLOWcE.js:62:2141)
```

**Comment by boojack** [comment]
I think it's been fixed as the demo site is working fine. https://demo.usememos.com/m/FqaZcg5H6EdGB9ke8kYUcy

**Comment by ertuil** [comment]
It works for my instance.
