### ISSUE TITLE
How to add CA  certificate to transport to solve tls issue 

### ISSUE THREAD

**Issue by jeven2016** [usememos/memos#2985]
### Describe the bug

Hi team, 
a issue encountered while integrating memos with keycloak over HTTPS , How to add CA  certificate to transport to solve tls issue ?

AuthCallback-nZeiGzTm.js:1 ClientError: /memos.api.v2.AuthService/SignInWithSSO INTERNAL: failed to exchange token, err: failed to exchange access token: Post "https://iam.super666.xyz/realms/home/protocol/openid-connect/token": tls: failed to verify certificate: x509: certificate signed by unknown authority
    at makeCall (index-vC1BnKoH.js:306:6112)
    at async at (index-vC1BnKoH.js:306:11471)
    at async Object.signInWithSSO (index-vC1BnKoH.js:306:11982)

### Steps to reproduce

keycloak exposes on HTTPS
but memos failed to call https api

### The version of Memos you're using

latest

### Screenshots or additional context

![image](https://github.com/usememos/memos/assets/21193241/d66f59c6-e97c-46a7-add9-c76f0a1a2300)

**Comment by jeven2016** [comment]
close

**Comment by jeven2016** [comment]
close
