### ISSUE TITLE
Memos crashes on Loongson browser

### ISSUE THREAD

**Issue by ladeng07** [usememos/memos#3013]
### Describe the bug

When I open memes on the Loongson browser, the following error occurs:

> Unexpected Application Error!
window.parse is not a function
TypeError: window.parse is not a function
    at q3 (http://memos.lmark.cc/assets/index-C-TcBniU.js:354:10589)
    at Xh (http://memos.lmark.cc/assets/index-DfuI4x39.js:75:21707)
    at dj (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:3491)
    at cj (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:2624)
    at aj (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:2093)
    at Wk (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:52182)
    at Vk (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:43777)
    at Uk (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:43700)
    at Jk (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:43542)
    at Ok (http://memos.lmark.cc/assets/index-DfuI4x39.js:77:39552)

### Steps to reproduce

1.Open memories in Loongson browser

### The version of Memos you're using

0.20.0

**Comment by boojack** [comment]
Sorry, we don't have resources to support non-mainstream browsers. Maybe you should use the following recommended browsers: https://developer.mozilla.org/en-US/docs/WebAssembly/JavaScript_interface#browser_compatibility
