### ISSUE TITLE
Uncaught ClientError returned for v0.21.0

### ISSUE THREAD

**Issue by jhademcconnell** [usememos/memos#3324]
### Describe the bug

After merging the latest v0.21.0 release, an error is returned in the memos instance. This memos instance uses postgreSQL as the database:

`
Uncaught (in promise) ClientError: /memos.api.v1.WorkspaceSettingService/ListWorkspaceSettings INTERNAL: failed to get workspace setting: Failed to convert workspace setting: unsupported workspace setting key: server-id
    at makeCall (index-CoeOqPkC.js:287:6118)
    at async at (index-CoeOqPkC.js:287:11481)
    at async Object.listWorkspaceSettings (index-CoeOqPkC.js:287:11992)
    at async Object.listWorkspaceSettings (index-CoeOqPkC.js:322:7580)
    at async lt (index-CoeOqPkC.js:322:13108)
    at async Promise.all (/index 0)
`

### Steps to reproduce

1. Navigate to memos instance
2. white page is returned, check the dev console
3. ClientError is returned in console

### The version of Memos you're using

v0.21.0

**Comment by Brian099** [comment]
+1
Uncaught (in promise) ClientError: /memos.api.v1.MemoService/ListMemos INTERNAL: failed to convert memo: failed to list memo resources: rpc error: code = Internal desc = failed to list resources
    at makeCall (index-Cqx9HcC8.js:287:6118)
    at async at (index-Cqx9HcC8.js:287:11481)
    at async Object.listMemos (index-Cqx9HcC8.js:287:11992)
    at async Object.fetchMemos (index-Cqx9HcC8.js:322:4618)
    at async ut (index-Cqx9HcC8.js:8019:50406)

**Comment by boojack** [comment]
> /memos.api.v1.WorkspaceSettingService/ListWorkspaceSettings INTERNAL: failed to get workspace setting: Failed to convert workspace setting: unsupported workspace setting key

Fixed with https://github.com/usememos/memos/commit/e16546f80aeeb85d9ad55ef6266addc7e0dae78e
