### ISSUE TITLE
Cannot read properties of undefined (reading 'hasLink') error

### ISSUE THREAD

**Issue by hackey90** [usememos/memos#3822]
### Describe the bug

I upgrade Memos from 0.21.0 to 0.22.4
when finished upgrade  (use docker) , when I click the add comment button it will got following error : 
============================
Unexpected Application Error!
Cannot read properties of undefined (reading 'hasLink')
TypeError: Cannot read properties of undefined (reading 'hasLink')
    at MemoDetailSidebar (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:8127:94698)
    at Nh (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:68:18867)
    at Vk (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:70:48341)
    at Uk (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:70:43659)
    at Tk (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:70:43582)
    at Ik (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:70:43424)
    at Nk (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:70:39460)
    at Gk (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:70:38302)
    at Et (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:55:1729)
    at MessagePort.Nt (http://hackey.asuscomm.com:5230/assets/index-DJ8SSNFr.js:55:2141)

### Steps to reproduce

1.upgrade 0.21.0 to 0.22.4 use docker 
2. click the comment button at history note . 
3. the website will jump to error page 

### The version of Memos you're using.

0.22.4

### Screenshots or additional context

![image](https://github.com/user-attachments/assets/2e59c8e9-d349-488c-8012-fa284fc3c697)
![image](https://github.com/user-attachments/assets/13bb9af1-fc59-456a-826d-0ac650a5466e)

**Comment by hackey90** [comment]
and tags missing too

**Comment by hackey90** [comment]
looks need reindex the notes

**Comment by boojack** [comment]
Might be fixed in `v0.22.5`. Please feel free to reopen this if issue still exists.
