### ISSUE TITLE
Cannot read properties of undefined (reading 'role')

### ISSUE THREAD

**Issue by pedrosouza458** [usememos/memos#3872]
### Describe the bug

Im getting this error when i try to access the demo:

```
Unexpected Application Error!
Cannot read properties of undefined (reading 'role')
TypeError: Cannot read properties of undefined (reading 'role')
    at isSuperUser (https://demo.usememos.com/assets/index-DtEUN4hn.js:718:38678)
    at MemoView (https://demo.usememos.com/assets/index-DtEUN4hn.js:1128:68464)
    at Nh (https://demo.usememos.com/assets/index-DtEUN4hn.js:68:18867)
    at cj (https://demo.usememos.com/assets/index-DtEUN4hn.js:70:3489)
    at bj (https://demo.usememos.com/assets/index-DtEUN4hn.js:70:2622)
    at $i (https://demo.usememos.com/assets/index-DtEUN4hn.js:70:2091)
    at Vk (https://demo.usememos.com/assets/index-DtEUN4hn.js:70:52048)
    at Uk (https://demo.usememos.com/assets/index-DtEUN4hn.js:70:43655)
    at Tk (https://demo.usememos.com/assets/index-DtEUN4hn.js:70:43578)
    at Ik (https://demo.usememos.com/assets/index-DtEUN4hn.js:70:43420)
```

### Steps to reproduce

1. Go to https://demo.usememos.com/explore

### The version of Memos you're using.

latest

### Screenshots or additional context

<img width="1440" alt="Captura de Tela 2024-09-02 às 21 42 51" src="https://github.com/user-attachments/assets/a40cb097-71b3-43cd-bab5-f19d37b363f6">

**Comment by RoccoSmit** [comment]
Are you still getting the issue? I'm unable to replicate. Demo loads without issues for me
