### ISSUE TITLE
prod 不能注册登录啊？日志里面只有一堆空指针

### ISSUE THREAD

**Issue by biluohc** [usememos/memos#90]
自动跳到/signin怎么填都是401， 开发环境的那个帐号也不能用， 删了那个db文件重来也不行

```sh
docker run -d \
	--name memos \
	--log-opt max-size=30m \
    	--log-opt max-file=2 \
    	--restart always \
	--publish 5230:5230 \
	--volume /opt/memos:/var/opt/memos \
	-e mode=prod -e port=5230 \
	neosmemo/memos:0.1.2
```

```sh
Version 0.1.2 has started at :5230
GET /api/user/me 401
echo: http: panic serving 192.168.1.8:33040: runtime error: invalid memory address or nil pointer dereference
goroutine 10 [running]:
net/http.(*conn).serve.func1(0xc0000a15e0)
	/usr/local/go/src/net/http/server.go:1805 +0x153
panic(0x9bfac0, 0xd61e40)
	/usr/local/go/src/runtime/panic.go:971 +0x499
net/http.(*timeoutHandler).ServeHTTP(0xc0001940c0, 0xaec250, 0xc00019a000, 0xc0000e4300)
	/usr/local/go/src/net/http/server.go:3302 +0x949
github.com/labstack/echo/v4/middleware.TimeoutWithConfig.func1.1(0xaf4698, 0xc0001a0000, 0xdcda40, 0x203000)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.6.3/middleware/timeout.go:118 +0x292
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1(0xaf4698, 0xc0001a0000, 0x0, 0x0)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.6.3/middleware/logger.go:117 +0x12c
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0000ab200, 0xaec250, 0xc00019a000, 0xc0000e4300)
	/go/pkg/mod/github.com/labstack/echo/v4@v4.6.3/echo.go:663 +0x2bc
net/http.serverHandler.ServeHTTP(0xc0000ee1c0, 0xaec250, 0xc00019a000, 0xc0000e4300)
	/usr/local/go/src/net/http/server.go:2868 +0xa3
net/http.(*conn).serve(0xc0000a15e0, 0xaecfc0, 0xc000130240)
	/usr/local/go/src/net/http/server.go:1933 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2994 +0x39b
```

**Comment by boojack** [comment]
感谢反馈，复现了，这几天会尝试修复

**Comment by boojack** [comment]
Thanks @hyoban contribution! Fixed in latest v0.1.2.
